# This project was developed with assistance from AI tools.
__version__ = "0.1.0"

from .database import (
    Base,
    ComplianceSessionLocal,
    DatabaseService,
    get_compliance_db,
    get_db,
    get_db_service,
)
from .enums import (
    ApplicationStage,
    ConditionSeverity,
    ConditionStatus,
    DecisionType,
    DocumentStatus,
    DocumentType,
    EmploymentStatus,
    ExtractionMethod,
    LoanType,
    PolicyJurisdiction,
    PolicySourceType,
    UserRole,
)
from .models import (
    Application,
    ApplicationBorrower,
    ApplicationFinancials,
    AuditEvent,
    AuditViolation,
    Borrower,
    ComplianceResult,
    Condition,
    CreditReport,
    Decision,
    DemoDataManifest,
    Document,
    DocumentExtraction,
    ExtractionCorrection,
    HmdaDemographic,
    HmdaLoanData,
    KBChunk,
    KBDocument,
    PrequalificationDecision,
    RateLock,
    RiskAssessmentRecord,
)

__all__ = [
    "Base",
    "ComplianceSessionLocal",
    "DatabaseService",
    "get_compliance_db",
    "get_db",
    "get_db_service",
    "__version__",
    # Enums
    "ApplicationStage",
    "UserRole",
    "LoanType",
    "DocumentType",
    "DocumentStatus",
    "ExtractionMethod",
    "EmploymentStatus",
    "PolicyJurisdiction",
    "PolicySourceType",
    "ConditionSeverity",
    "ConditionStatus",
    "DecisionType",
    # Models
    "Application",
    "ApplicationBorrower",
    "ApplicationFinancials",
    "AuditEvent",
    "AuditViolation",
    "Borrower",
    "ComplianceResult",
    "Condition",
    "CreditReport",
    "Decision",
    "DemoDataManifest",
    "Document",
    "DocumentExtraction",
    "ExtractionCorrection",
    "HmdaDemographic",
    "HmdaLoanData",
    "KBChunk",
    "KBDocument",
    "PrequalificationDecision",
    "RateLock",
    "RiskAssessmentRecord",
]
